all: sales_problem  nfl_problem

sales_problem: sales_problem.c
	gcc -o sales_problem sales_problem.c
nfl_problem: nfl_problem.c 
	gcc -o nfl_problem nfl_problem.c
clean:
	rm -f sales_problem 
	rm -f nfl_problem
